name: GitHub Actions Demo
on: 
  workflow_dispatch:
    inputs:
        environment:
        description: Environment to run tests against
        type: environment
        required: true 
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      - run: npm run build
